version: "3.8"

services:
    flask_api_gpt:
        networks:
            - ai_net
        build: .
        restart: on-failure
        command: python3 app.py
        volumes:
            - ./src/:/app/src/
            - ./app.py:/app/app.py
        ports:
            - "5001:5000"
        environment:
            - FLASK_ENV=development
        env_file:
            - .env

networks:
    ai_net:
        driver: bridge
