version: "3.8"

services:
    model_api:
        networks:
            - ai_net
        image: hyperonym/basaran:0.14.1
        restart: on-failure
        environment:
            MODEL: "/models/bloomz-3b"
            SERVER_MODEL_NAME: "bloomz-3b"
            MODEL_HALF_PRECISION: "true"
            CUDA_MEMORY_FRACTION: "1.0"
            # MODEL_LOAD_IN_8BIT: "true"  # single-GPU
        ports:
            - 7000:80
        # expose:
        #     - "80"
        volumes:
            - ./torchserve/models/:/models/
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

    flask_api:
        networks:
            - ai_net
        build: .
        restart: on-failure
        command: python3 app.py
        volumes:
            - .:/app
        ports:
            - "5000:5000"

networks:
    ai_net:
        driver: bridge
