version: "3.8"

services:
    basaran:
        image: hyperonym/basaran:0.14.1
        restart: always
        environment:
            MODEL: "/models/bigscience/bloomz-560m/"
            SERVER_MODEL_NAME: "bigscience/bloomz-560m"
            MODEL_HALF_PRECISION: "true"
            CUDA_MEMORY_FRACTION: "1.0"
        ports:
            - "3000:80"
        volumes:
            - ./models_mount:/models/
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
